import type { MarketplaceVehicleRaw } from "@/types/api";

export const MOCK_MARKETPLACE_LISTINGS: MarketplaceVehicleRaw[] = [
  {
    id: "mock-1",
    title: "Ferrari 488 GTB",
    make: "Ferrari",
    model: "488 GTB",
    year: 2019,
    colour: "Rosso Corsa",
    vehicleType: "Supercar",
    mileage: 12400,
    mileageLabel: "12,400 km",
    priceAed: 1250000,
    priceLabel: "AED 1,250,000",
    currency: "AED",
    status: "available",
    statusLabel: "Available",
    isFeatured: true,
    isFavorited: false,
    coverImage: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=800&q=80",
    images: ["https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=800&q=80"],
    description:
      "A stunning example in Rosso Corsa with full service history. One owner from new with all original books and keys. Carbon fibre package fitted.",
    highlights: [
      "Full Ferrari service history",
      "Carbon fibre interior package",
      "Panoramic roof",
      "Single owner from new",
    ],
    engineType: "3.9L V8 Twin-Turbo",
    transmission: "7-Speed DCT",
    fuelType: "Petrol",
    power: "660 hp",
    zeroToHundred: "3.0s",
    topSpeed: "330 km/h",
    sellerType: "club",
    sellerName: "ToyBox Collection",
    listedAt: "2025-07-01T00:00:00Z",
  },
  {
    id: "mock-2",
    title: "Porsche 911 GT3 RS",
    make: "Porsche",
    model: "911 GT3 RS",
    year: 2022,
    colour: "Guards Red",
    vehicleType: "Sports Car",
    mileage: 5800,
    mileageLabel: "5,800 km",
    priceAed: 980000,
    priceLabel: "AED 980,000",
    currency: "AED",
    status: "available",
    statusLabel: "Available",
    isFeatured: true,
    isFavorited: false,
    coverImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
    images: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80"],
    description:
      "Motorsport-derived naturally aspirated 4.0L flat-six. Weissach package fitted. The definitive road-legal track weapon from Porsche.",
    highlights: [
      "Weissach package",
      "PCCB ceramic brakes",
      "Clubsport roll cage",
      "Full cage harness",
    ],
    engineType: "4.0L Flat-Six NA",
    transmission: "7-Speed PDK",
    fuelType: "Petrol",
    power: "525 hp",
    zeroToHundred: "3.2s",
    topSpeed: "296 km/h",
    sellerType: "member",
    sellerName: "Private Member",
    listedAt: "2025-07-05T00:00:00Z",
  },
  {
    id: "mock-3",
    title: "Lamborghini Huracán EVO",
    make: "Lamborghini",
    model: "Huracán EVO",
    year: 2021,
    colour: "Arancio Borealis",
    vehicleType: "Supercar",
    mileage: 9200,
    mileageLabel: "9,200 km",
    priceAed: 1450000,
    priceLabel: "AED 1,450,000",
    currency: "AED",
    status: "available",
    statusLabel: "Available",
    isFeatured: false,
    isFavorited: false,
    coverImage: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80",
    images: ["https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80"],
    description:
      "Arancio Borealis with black Alcantara interior. LDVI predictive AWD system and ALA 2.0 active aerodynamics.",
    engineType: "5.2L V10 NA",
    transmission: "7-Speed LDF",
    fuelType: "Petrol",
    power: "640 hp",
    zeroToHundred: "2.9s",
    topSpeed: "325 km/h",
    sellerType: "club",
    sellerName: "ToyBox Collection",
    listedAt: "2025-07-08T00:00:00Z",
  },
  {
    id: "mock-4",
    title: "McLaren 720S",
    make: "McLaren",
    model: "720S",
    year: 2020,
    colour: "Papaya Spark",
    vehicleType: "Supercar",
    mileage: 18700,
    mileageLabel: "18,700 km",
    priceAed: 895000,
    priceLabel: "AED 895,000",
    currency: "AED",
    status: "reserved",
    statusLabel: "Reserved",
    isFeatured: false,
    isFavorited: false,
    coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80"],
    description:
      "Performance Pack fitted. MSO satin Papaya Spark with full black leather and electrochromic roof panel.",
    engineType: "4.0L V8 Twin-Turbo",
    transmission: "7-Speed SSG",
    fuelType: "Petrol",
    power: "720 hp",
    zeroToHundred: "2.9s",
    topSpeed: "341 km/h",
    sellerType: "member",
    sellerName: "Private Member",
    listedAt: "2025-06-20T00:00:00Z",
  },
  {
    id: "mock-5",
    title: "Aston Martin DB11 V12",
    make: "Aston Martin",
    model: "DB11",
    year: 2020,
    colour: "Midnight Blue",
    vehicleType: "Grand Tourer",
    mileage: 22100,
    mileageLabel: "22,100 km",
    priceAed: 620000,
    priceLabel: "AED 620,000",
    currency: "AED",
    status: "available",
    statusLabel: "Available",
    isFeatured: false,
    isFavorited: true,
    coverImage: "https://images.unsplash.com/photo-1621135802920-133df287f89c?w=800&q=80",
    images: ["https://images.unsplash.com/photo-1621135802920-133df287f89c?w=800&q=80"],
    description:
      "Midnight Blue over Obsidian Black full leather interior. Twin-turbo V12 Grand Tourer in exceptional condition.",
    engineType: "5.2L V12 Twin-Turbo",
    transmission: "8-Speed ZF Auto",
    fuelType: "Petrol",
    power: "630 hp",
    zeroToHundred: "3.7s",
    topSpeed: "322 km/h",
    sellerType: "member",
    sellerName: "Private Member",
    listedAt: "2025-06-15T00:00:00Z",
  },
  {
    id: "mock-6",
    title: "Bentley Continental GT Speed",
    make: "Bentley",
    model: "Continental GT Speed",
    year: 2022,
    colour: "Verdant",
    vehicleType: "Grand Tourer",
    mileage: 8400,
    mileageLabel: "8,400 km",
    priceAed: 1180000,
    priceLabel: "AED 1,180,000",
    currency: "AED",
    status: "available",
    statusLabel: "Available",
    isFeatured: false,
    isFavorited: false,
    coverImage: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
    images: ["https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80"],
    description:
      "Speed variant in rare Verdant green with Beluga hide. Rotating dashboard, city specification and Naim audio system.",
    engineType: "6.0L W12 Twin-Turbo",
    transmission: "8-Speed DCT",
    fuelType: "Petrol",
    power: "659 hp",
    zeroToHundred: "3.6s",
    topSpeed: "335 km/h",
    sellerType: "club",
    sellerName: "ToyBox Collection",
    listedAt: "2025-07-10T00:00:00Z",
  },
  {
    id: "mock-7",
    title: "Mercedes-AMG GT Black Series",
    make: "Mercedes-AMG",
    model: "GT Black Series",
    year: 2021,
    colour: "Selenite Grey",
    vehicleType: "Track Car",
    mileage: 3200,
    mileageLabel: "3,200 km",
    priceAed: 2100000,
    priceLabel: "AED 2,100,000",
    currency: "AED",
    status: "available",
    statusLabel: "Available",
    isFeatured: false,
    isFavorited: false,
    coverImage: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80",
    images: ["https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80"],
    description:
      "The most extreme AMG GT ever made. Flat-plane crank V8, active rear-axle steering, and full carbon aero package.",
    engineType: "4.0L V8 Flat-Plane",
    transmission: "7-Speed DCT",
    fuelType: "Petrol",
    power: "730 hp",
    zeroToHundred: "3.2s",
    topSpeed: "325 km/h",
    sellerType: "member",
    sellerName: "Private Member",
    listedAt: "2025-07-12T00:00:00Z",
  },
  {
    id: "mock-8",
    title: "Rolls-Royce Ghost Black Badge",
    make: "Rolls-Royce",
    model: "Ghost Black Badge",
    year: 2023,
    colour: "Black Diamond",
    vehicleType: "Luxury Saloon",
    mileage: 4100,
    mileageLabel: "4,100 km",
    priceAed: 3200000,
    priceLabel: "AED 3,200,000",
    currency: "AED",
    status: "available",
    statusLabel: "Available",
    isFeatured: false,
    isFavorited: false,
    coverImage: "https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&q=80",
    images: ["https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&q=80"],
    description:
      "Bespoke Black Badge commission in Black Diamond with starlight headliner. Fully optioned with rear theatre configuration.",
    engineType: "6.75L V12 Twin-Turbo",
    transmission: "8-Speed Automatic",
    fuelType: "Petrol",
    power: "600 hp",
    zeroToHundred: "4.5s",
    topSpeed: "250 km/h",
    sellerType: "member",
    sellerName: "Private Member",
    listedAt: "2025-07-14T00:00:00Z",
  },
  {
    id: "mock-9",
    title: "Pagani Huayra Roadster",
    make: "Pagani",
    model: "Huayra Roadster",
    year: 2018,
    colour: "Bianco Perla",
    vehicleType: "Hypercar",
    mileage: 1900,
    mileageLabel: "1,900 km",
    priceAed: 18500000,
    priceLabel: "AED 18,500,000",
    currency: "AED",
    status: "available",
    statusLabel: "Available",
    isFeatured: false,
    isFavorited: false,
    coverImage: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80",
    images: ["https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80"],
    description:
      "One of only 100 Huayra Roadsters built. Bianco Perla with bespoke Pagani luggage set. Complete with all documentation and transport crate.",
    highlights: [
      "1 of 100 worldwide",
      "Bespoke Pagani luggage set",
      "AMG V12 biturbo",
      "Full Pagani service history",
    ],
    engineType: "6.0L V12 Twin-Turbo (AMG)",
    transmission: "7-Speed Sequential",
    fuelType: "Petrol",
    power: "764 hp",
    zeroToHundred: "2.8s",
    topSpeed: "383 km/h",
    sellerType: "club",
    sellerName: "ToyBox Collection",
    listedAt: "2025-07-15T00:00:00Z",
  },
  {
    id: "mock-10",
    title: "Bugatti Chiron Sport",
    make: "Bugatti",
    model: "Chiron Sport",
    year: 2020,
    colour: "French Racing Blue",
    vehicleType: "Hypercar",
    mileage: 2700,
    mileageLabel: "2,700 km",
    priceAed: 26000000,
    priceLabel: "AED 26,000,000",
    currency: "AED",
    status: "available",
    statusLabel: "Available",
    isFeatured: false,
    isFavorited: false,
    coverImage: "https://images.unsplash.com/photo-1544502062-f82887f03d1c?w=800&q=80",
    images: ["https://images.unsplash.com/photo-1544502062-f82887f03d1c?w=800&q=80"],
    description:
      "Sport specification with carbon fibre windscreen surround and lightweight titanium exhaust. French Racing Blue with Beluga black interior.",
    highlights: [
      "Carbon windscreen surround",
      "Titanium exhaust system",
      "Sport suspension",
      "Bugatti certified",
    ],
    engineType: "8.0L W16 Quad-Turbo",
    transmission: "7-Speed DSG",
    fuelType: "Petrol",
    power: "1500 hp",
    zeroToHundred: "2.4s",
    topSpeed: "420 km/h",
    sellerType: "club",
    sellerName: "ToyBox Collection",
    listedAt: "2025-07-16T00:00:00Z",
  },
];
