import type { ActiveBayItem, ServiceQueueItem, WorkshopStatItem } from "./types";

export const workshopStats: WorkshopStatItem[] = [
  {
    label: "Active Jobs",
    value: "12",
    footnote: "In Progress",
  },
  {
    label: "Overdue",
    value: "3",
    footnote: "Critical",
    valueTone: "pink",
    iconTone: "pink",
  },
  {
    label: "Awaiting Parts",
    value: "5",
    footnote: "OEM Order",
    valueTone: "gold",
  },
  {
    label: "Avg Turnaround",
    value: "4.8 Days",
    footnote: "30D Avg",
    valueTone: "white",
    trend: "-0.6D",
  },
  {
    label: "Engineers On",
    value: "5",
    footnote: "Marco + 4",
    valueTone: "white",
  },
];

export const activeBays: ActiveBayItem[] = [
  {
    id: "bay-03",
    bay: "BAY 03",
    status: "overdue",
    statusLabel: "Overdue 12D",
    vehicleMake: "Ferrari",
    vehicleModel: "296 GTB",
    memberName: "Mitchell",
    memberNumber: "0004192",
    description:
      "Major service — gearbox seal, brake fluid, valve service. Awaiting OEM seal kit (ETA 12 May).",
    engineer: "Marco",
    engineerRole: "Lead",
    timeLabel: "+12d",
    timeTone: "pink",
  },
  {
    id: "bay-05",
    bay: "BAY 05",
    status: "overdue",
    statusLabel: "Overdue 8D",
    vehicleMake: "Lamborghini",
    vehicleModel: "Revuelto",
    memberName: "Hassan",
    memberNumber: "0003106",
    description:
      "Carbon ceramic brake replacement. Member notified · parts delayed Italy.",
    engineer: "Dario",
    timeLabel: "+8d",
    timeTone: "pink",
  },
  {
    id: "bay-04b",
    bay: "BAY 04B",
    status: "overdue",
    statusLabel: "Overdue 5D",
    vehicleMake: "Rolls-Royce",
    vehicleModel: "Spectre",
    memberName: "Al Habibi",
    memberNumber: "0002104",
    description:
      "Annual service · paint correction. Awaiting OEM paint sample for door panel.",
    engineer: "Sven",
    timeLabel: "+5d",
    timeTone: "pink",
  },
  {
    id: "bay-07",
    bay: "BAY 07",
    status: "active",
    statusLabel: "Active",
    vehicleMake: "Mercedes Maybach",
    vehicleModel: "S 680",
    memberName: "Khoury",
    memberNumber: "0003812",
    description:
      "Tyre rotation, full detail, interior conditioning. Return today 18:00.",
    engineer: "Marco",
    timeLabel: "Today 18:00",
    timeTone: "gold",
  },
  {
    id: "bay-09b",
    bay: "BAY 09B",
    status: "active",
    statusLabel: "Active",
    vehicleMake: "Aston Martin",
    vehicleModel: "V12 Vantage",
    memberName: "Khalili",
    memberNumber: "0002391",
    description: "Suspension geometry, ECU update. On schedule.",
    engineer: "Dario",
    timeLabel: "Today 18:00",
    timeTone: "gold",
  },
  {
    id: "bay-10",
    bay: "BAY 10",
    status: "final-check",
    statusLabel: "Final Check",
    vehicleMake: "Bentley",
    vehicleModel: "Mulsanne",
    memberName: "Patel",
    memberNumber: "0003220",
    description:
      "Oil service, valet detail, leather treatment. Quality check in progress.",
    engineer: "Marco",
    timeLabel: "Ready 14:00",
    timeTone: "teal",
  },
];

export const serviceQueue: ServiceQueueItem[] = [
  {
    id: "sq-1",
    date: "Mon 11",
    memberInitial: "P",
    memberName: "Mr. Patel",
    memberNumber: "0003220",
    vehicleMake: "Aston Martin",
    vehicleModel: "DBS Superleggera",
    service: "Annual service",
    engineer: "Marco",
    estimate: "3d",
  },
  {
    id: "sq-2",
    date: "Tue 12",
    memberInitial: "N",
    memberName: "Mrs. Nasser",
    memberNumber: "0002981",
    vehicleMake: "Ferrari",
    vehicleModel: "SF90 Stradale",
    service: "Pre-track prep",
    engineer: "Marco · Sven",
    estimate: "1d",
  },
  {
    id: "sq-3",
    date: "Wed 13",
    memberInitial: "M",
    memberName: "Mr. Mitchell",
    memberNumber: "0004192",
    vehicleMake: "Ferrari",
    vehicleModel: "296 GTB",
    service: "Major service completion",
    engineer: "Marco",
    estimate: "2d",
  },
  {
    id: "sq-4",
    date: "Fri 15",
    memberInitial: "B",
    memberName: "Mr. Bashir",
    memberNumber: "0001847",
    vehicleMake: "Bentley",
    vehicleModel: "Continental GT",
    service: "Brake service",
    engineer: "Dario",
    estimate: "1d",
  },
];
