import type { FleetHealthItem, HealthReport } from "./types";

export const fleetHealthItems: FleetHealthItem[] = [
  {
    id: "ferrari-296",
    vehicle: "Ferrari 296 GTB",
    bay: "A-03",
    member: "Khalid Al Mansoori",
    mileage: "41,200 km",
    healthPercent: 42,
    healthStatus: "critical",
  },
  {
    id: "lamborghini-huracan",
    vehicle: "Lamborghini Huracan",
    bay: "B-07",
    member: "Sarah Mitchell",
    mileage: "28,450 km",
    healthPercent: 68,
    healthStatus: "due-service",
  },
  {
    id: "porsche-911",
    vehicle: "Porsche 911 Turbo S",
    bay: "A-11",
    member: "James Chen",
    mileage: "19,800 km",
    healthPercent: 91,
    healthStatus: "good",
  },
  {
    id: "mclaren-720s",
    vehicle: "McLaren 720S",
    bay: "C-02",
    member: "Elena Rossi",
    mileage: "12,300 km",
    healthPercent: 96,
    healthStatus: "excellent",
  },
];

export const healthReports: Record<string, HealthReport> = {
  "ferrari-296": {
    id: "ferrari-296",
    reference: "HLT-0288",
    vehicle: "Ferrari 296 GTB",
    yearColorBay: "2023 · Rosso Corsa · Bay A-03",
    healthPercent: 42,
    healthStatus: "critical",
    isOverdue: true,
    overdueDays: 12,
    overdueSummary:
      "Ferrari 296 GTB · Annual service was due 7 May 2026 · Immediate action required",
    mileage: "41,200 km",
    lastService: "Jan 2026",
    member: "Katherine Monroe",
    serviceDue: "7 May 2026",
    overallCondition: "Critical — Service Overdue",
    systemMetrics: [
      { label: "Engine & Drivetrain", value: 38, tone: "pink" },
      { label: "Tyres", value: 55, tone: "gold" },
      { label: "Brakes", value: 44, tone: "pink" },
      { label: "Battery", value: 92, tone: "teal" },
      { label: "Fluids", value: 62, tone: "gold" },
      { label: "Exterior & Body", value: 90, tone: "teal" },
      { label: "Interior", value: 88, tone: "teal" },
      { label: "Electronics", value: 75, tone: "teal" },
    ],
    flaggedIssues: [
      {
        id: "1",
        title: "Annual Service Overdue — 12 Days",
        description:
          "Engine oil degraded · Service was due 7 May 2026 · High urgency",
        actionLabel: "BOOK NOW",
      },
      {
        id: "2",
        title: "Brake Pads — Front Left Wear 44%",
        description: "Replace before next drive · High urgency",
        actionLabel: "BOOK NOW",
      },
      {
        id: "3",
        title: "Tyre Tread Depth — Front Pair 55%",
        description: "Monitor — schedule replacement within 3 months",
        actionLabel: "SCHEDULE",
      },
    ],
    serviceHistory: [
      {
        id: "1",
        date: "7 Jan 2026",
        title: "Annual Service — Official Ferrari Centre",
        location: "AED 8,200 · 38,800 km",
        detail: "Completed",
      },
      {
        id: "2",
        date: "15 Oct 2025",
        title: "Full Detail + Ceramic Coat Maintenance",
        location: "AED 2,400 · 35,200 km",
        detail: "Completed",
      },
      {
        id: "3",
        date: "22 Jun 2025",
        title: "Annual Service — Official Ferrari Centre",
        location: "AED 7,900 · 29,400 km",
        detail: "Completed",
      },
      {
        id: "4",
        date: "3 Mar 2025",
        title: "Tyre Replacement — All Four",
        location: "AED 5,600 · 26,100 km",
        detail: "Completed",
      },
    ],
  },
  "lamborghini-huracan": {
    id: "lamborghini-huracan",
    reference: "HLT-0291",
    vehicle: "Lamborghini Huracan",
    yearColorBay: "2022 · Verde Mantis · Bay B-07",
    healthPercent: 68,
    healthStatus: "due-service",
    isOverdue: false,
    mileage: "28,450 km",
    lastService: "Nov 2025",
    member: "Sarah Mitchell",
    serviceDue: "15 Aug 2026",
    overallCondition: "Due Service — Schedule Soon",
    systemMetrics: [
      { label: "Engine & Drivetrain", value: 72, tone: "gold" },
      { label: "Tyres", value: 65, tone: "gold" },
      { label: "Brakes", value: 58, tone: "gold" },
      { label: "Battery", value: 88, tone: "teal" },
      { label: "Fluids", value: 70, tone: "gold" },
      { label: "Exterior & Body", value: 85, tone: "teal" },
      { label: "Interior", value: 82, tone: "teal" },
      { label: "Electronics", value: 78, tone: "teal" },
    ],
    flaggedIssues: [
      {
        id: "1",
        title: "Service Due in 45 Days",
        description: "Annual service approaching · Schedule at convenience",
        actionLabel: "SCHEDULE",
      },
    ],
    serviceHistory: [
      {
        id: "1",
        date: "12 Nov 2025",
        title: "Annual Service — Lamborghini Centre",
        location: "AED 6,400 · 24,100 km",
        detail: "Completed",
      },
    ],
  },
  "porsche-911": {
    id: "porsche-911",
    reference: "HLT-0304",
    vehicle: "Porsche 911 Turbo S",
    yearColorBay: "2024 · GT Silver · Bay A-11",
    healthPercent: 91,
    healthStatus: "good",
    isOverdue: false,
    mileage: "19,800 km",
    lastService: "Feb 2026",
    member: "James Chen",
    serviceDue: "Feb 2027",
    overallCondition: "Good — No Immediate Action",
    systemMetrics: [
      { label: "Engine & Drivetrain", value: 92, tone: "teal" },
      { label: "Tyres", value: 88, tone: "teal" },
      { label: "Brakes", value: 90, tone: "teal" },
      { label: "Battery", value: 95, tone: "teal" },
      { label: "Fluids", value: 89, tone: "teal" },
      { label: "Exterior & Body", value: 94, tone: "teal" },
      { label: "Interior", value: 91, tone: "teal" },
      { label: "Electronics", value: 93, tone: "teal" },
    ],
    flaggedIssues: [],
    serviceHistory: [
      {
        id: "1",
        date: "18 Feb 2026",
        title: "Annual Service — Porsche Centre",
        location: "AED 5,100 · 17,200 km",
        detail: "Completed",
      },
    ],
  },
  "mclaren-720s": {
    id: "mclaren-720s",
    reference: "HLT-0310",
    vehicle: "McLaren 720S",
    yearColorBay: "2023 · Papaya Spark · Bay C-02",
    healthPercent: 96,
    healthStatus: "excellent",
    isOverdue: false,
    mileage: "12,300 km",
    lastService: "Mar 2026",
    member: "Elena Rossi",
    serviceDue: "Mar 2027",
    overallCondition: "Excellent — Fleet Ready",
    systemMetrics: [
      { label: "Engine & Drivetrain", value: 97, tone: "teal" },
      { label: "Tyres", value: 95, tone: "teal" },
      { label: "Brakes", value: 96, tone: "teal" },
      { label: "Battery", value: 98, tone: "teal" },
      { label: "Fluids", value: 94, tone: "teal" },
      { label: "Exterior & Body", value: 97, tone: "teal" },
      { label: "Interior", value: 96, tone: "teal" },
      { label: "Electronics", value: 95, tone: "teal" },
    ],
    flaggedIssues: [],
    serviceHistory: [
      {
        id: "1",
        date: "4 Mar 2026",
        title: "Annual Service — McLaren Centre",
        location: "AED 7,300 · 10,800 km",
        detail: "Completed",
      },
    ],
  },
};
