import type { MemberDashboardData } from "./types";

export const memberDashboardMock: MemberDashboardData = {
  memberName: "Alex Mitchell",
  memberNumber: "No. 000195",
  membershipTier: "Founding Member",
  memberSince: "Since 2019",
  kpis: [
    { label: "Vehicles", value: "4", subtext: "In storage", iconKey: "vehicles", tone: "gold" },
    { label: "Active Requests", value: "2", subtext: "In progress", iconKey: "requests" },
    { label: "Upcoming Events", value: "3", subtext: "Pending", iconKey: "events" },
    { label: "Days as Member", value: "142", subtext: "Founding", iconKey: "days" },
  ],
  vehicles: [
    {
      id: "1",
      name: "Rolls-Royce Ghost Black Badge",
      plate: "B72 · 47K · 87 L A",
      status: "ready",
      statusLabel: "Ready",
      imageUrl: "https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=400&q=80",
      lastService: "Friday, 12 May",
      mileage: "Details",
      year: "2024",
      engine: "V12 EXTENDED",
      bay: "BAY 04A",
      odometer: "8,412 mi",
      inspected: "06:14 today",
    },
    {
      id: "2",
      name: "Bentley Continental GT Speed",
      plate: "F13 · 83J · 55 B M",
      status: "ready",
      statusLabel: "Ready",
      imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400&q=80",
      lastService: "13 APR · Full Fitting",
      mileage: "Details",
      year: "2023",
      engine: "W12 MULLINER",
      bay: "BAY 02B",
      odometer: "12,847 mi",
      inspected: "05:48 today",
    },
    {
      id: "3",
      name: "Ferrari 296 GTB",
      plate: "D33 · 90B · 11 F R",
      status: "in_service",
      statusLabel: "In Service",
      imageUrl: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=400&q=80",
      lastService: "Friday, 24 Nov · View Job",
      mileage: "Details",
      year: "2023",
      engine: "HYBRID V6",
      bay: "BAY D3",
      returns: "Friday, 26 Apr",
      engineer: "Marco",
    },
  ],
  diary: [
    {
      id: "1",
      title: "Auction Day — Yas Marina",
      location: "Yas Marina Circuit · Abu Dhabi",
      dateLabel: "26 APR",
      monthLabel: "APR",
      dayLabel: "26",
      dayName: "SAT",
      dateShort: "SAT 26 APR",
      time: "19:00",
      attendingCount: 18,
      userStatus: "going",
      tag: "TONIGHT",
      tagTone: "gold",
      imageUrl: "https://images.unsplash.com/photo-1504707748692-419802cf939d?w=600&q=80",
      isFeatured: true,
      status: "confirmed",
    },
    {
      id: "2",
      title: "Dawn Drive — Hatta",
      location: "05:30 · 12 Members",
      dateLabel: "27 APR",
      monthLabel: "APR",
      dayLabel: "27",
      dayName: "SUN",
      dateShort: "SUN 27 APR",
      time: "05:30",
      membersCount: 12,
      tag: "RSVP",
      tagTone: "gold",
      status: "upcoming",
    },
    {
      id: "3",
      title: "Collectors' Dinner",
      location: "20:00 · The Clubhouse",
      dateLabel: "29 APR",
      monthLabel: "APR",
      dayLabel: "29",
      dayName: "TUE",
      dateShort: "TUE 29 APR",
      time: "20:00",
      tag: "CONFIRMED",
      tagTone: "teal",
      status: "confirmed",
    },
    {
      id: "4",
      title: "Track Day — Yas Marina",
      location: "07:00 · BYO Car",
      dateLabel: "04 MAY",
      monthLabel: "MAY",
      dayLabel: "04",
      dayName: "MAY",
      dateShort: "MAY 04",
      time: "07:00",
      tag: "UPCOMING",
      tagTone: "gold",
      status: "upcoming",
    },
  ],
  clubStatusLine: "Dubai · Open until 02:00 · 14 Members in",
  clubVenues: [
    {
      id: "1",
      name: "The Clubhouse",
      description: "Restaurant, bar & private dining. Your usual table held until 22:00",
      imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&q=85",
      tag: "OPEN",
      tagTone: "gold",
      iconKey: "clubhouse",
      footerLeft: "14 IN · 21:30",
      actionLabel: "RESERVE",
    },
    {
      id: "2",
      name: "Members' Lounge",
      description: "Cigar room, library & private seating areas...",
      imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=900&q=85",
      tag: "QUIET",
      tagTone: "gold",
      iconKey: "lounge",
      footerLeft: "4 IN",
      actionLabel: "ENTER",
    },
    {
      id: "3",
      name: "Private Suites",
      description: "Four meeting rooms, all with concierge service.",
      imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&q=85",
      tag: "AVAILABLE",
      tagTone: "gold",
      iconKey: "suites",
      footerLeft: "4 ROOMS",
      actionLabel: "BOOK",
    },
  ],
  news: [
    {
      id: "1",
      title: "A new addition to the Club Garage",
      titlePrefix: "A new addition to the",
      titleHighlight: "Club Garage",
      category: "ACQUISITION",
      subtitle:
        "A 1967 Aston Martin DB6 has joined our shared collection — available for private viewing this weekend.",
      timeLabel: "2 hours ago",
      imageUrl: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=240&q=85",
      isUnread: true,
    },
    {
      id: "2",
      title: "Welcome to twelve new founding members",
      titlePrefix: "Welcome to",
      titleHighlight: "twelve new founding members",
      category: "MEMBER NEWS",
      subtitle:
        "A heartfelt welcome to our newest members joining the Toybox community this quarter.",
      timeLabel: "2 days ago",
      imageUrl: "https://images.unsplash.com/photo-1519641471654-76ce5427acb5?w=240&q=85",
      isUnread: true,
    },
    {
      id: "3",
      title: "Partnership with Pirelli Collezione",
      titlePrefix: "Partnership with",
      titleHighlight: "Pirelli Collezione",
      category: "NEWS",
      subtitle: "Exclusive tyre programme for classics — available to members from 1 May.",
      timeLabel: "1 week ago",
      imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=240&q=85",
      isUnread: false,
    },
  ],
  recentActivity: [
    {
      id: "1",
      title: "Ghost Black Badge — Detailed & Inspected",
      titlePrefix: "Ghost Black Badge",
      titleHighlight: "— Detailed & Inspected",
      detail: "47 inspection points completed by Marco at the Clubhouse workshop.",
      timeLabel: "Today · 06:14",
      tone: "gold",
    },
    {
      id: "2",
      title: "Cigar Evening — Members' Lounge",
      titlePrefix: "Cigar Evening",
      titleHighlight: "— Members' Lounge",
      detail: "A quiet evening with the Davidoff curation.",
      timeLabel: "Wed 23 Apr · 21:15",
      tone: "gold",
    },
    {
      id: "3",
      title: "Dawn Drive to Hatta",
      titlePrefix: "Dawn Drive to",
      titleHighlight: "Hatta",
      detail: "147 miles round trip with the Continental GT. Group of twelve.",
      timeLabel: "Mon 21 Apr · 06:00",
      tone: "gold",
    },
    {
      id: "4",
      title: "Collectors' Dinner — Clubhouse",
      titlePrefix: "Collectors' Dinner",
      titleHighlight: "— Clubhouse",
      detail: "Four-course tasting menu paired with rare Bordeaux.",
      timeLabel: "Wed 16 Apr · 20:00",
      tone: "gold",
    },
  ],
};
