import type { MemberDashboardData } from "./types";

export const memberDashboardMock: MemberDashboardData = {
  memberName: "Alex Mitchell",
  memberNumber: "No. 000195",
  membershipTier: "Founding Member",
  memberSince: "Since 2019",
  kpis: [
    { label: "Vehicles", value: "4", subtext: "In storage", iconKey: "vehicles", tone: "gold" },
    { label: "Active Requests", value: "2", subtext: "In progress", iconKey: "requests" },
    { label: "Upcoming Events", value: "3", subtext: "Pending", iconKey: "events" },
    { label: "Days as Member", value: "142", subtext: "Founding", iconKey: "days" },
  ],
  vehicles: [
    {
      id: "1",
      name: "Rolls-Royce Ghost Silver Spur",
      plate: "B72 · 47K · 87 L A",
      status: "ready",
      statusLabel: "Ready",
      imageUrl: "https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=400&q=80",
      lastService: "Friday, 12 May",
      mileage: "Details",
    },
    {
      id: "2",
      name: "Bentley Continental GT Speed",
      plate: "F13 · 83J · 55 B M",
      status: "in_service",
      statusLabel: "In Service",
      imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400&q=80",
      lastService: "13 APR · Full Fitting",
      mileage: "Details",
    },
    {
      id: "3",
      name: "Ferrari 296 GTB",
      plate: "D33 · 90B · 11 F R",
      status: "scheduled",
      statusLabel: "Scheduled",
      imageUrl: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=400&q=80",
      lastService: "Friday, 24 Nov · View Job",
      mileage: "Details",
    },
  ],
  diary: [
    {
      id: "1",
      title: "Abu Dhabi F1 — Yas Marina",
      location: "Yas Marina Circuit",
      dateLabel: "26 NOV",
      monthLabel: "NOV",
      dayLabel: "26",
      tag: "TODAY",
      tagTone: "teal",
      imageUrl: "https://images.unsplash.com/photo-1504707748692-419802cf939d?w=600&q=80",
      isFeatured: true,
      status: "confirmed",
    },
    {
      id: "2",
      title: "Bugatti Divo Launch",
      location: "Dubai Design District",
      dateLabel: "27 NOV",
      monthLabel: "NOV",
      dayLabel: "27",
      tag: "RSVP",
      tagTone: "gold",
      status: "upcoming",
    },
    {
      id: "3",
      title: "Clubhouse Dinner",
      location: "The Clubhouse · Level 3",
      dateLabel: "29 NOV",
      monthLabel: "NOV",
      dayLabel: "29",
      tag: "CONFIRMED",
      tagTone: "teal",
      status: "confirmed",
    },
    {
      id: "4",
      title: "Track Day on the Yas Marina",
      location: "Yas Marina Circuit · Abu Dhabi",
      dateLabel: "04 DEC",
      monthLabel: "DEC",
      dayLabel: "04",
      tag: "UPCOMING",
      tagTone: "gold",
      status: "upcoming",
    },
  ],
  clubVenues: [
    {
      id: "1",
      name: "The Clubhouse",
      description: "Fine dining and lounge",
      imageUrl: "https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=600&q=80",
      tag: "OPEN",
      tagTone: "teal",
    },
    {
      id: "2",
      name: "Members Lounge",
      description: "Private relaxation floor",
      imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80",
      tag: "OPEN",
      tagTone: "teal",
    },
    {
      id: "3",
      name: "Private Suites",
      description: "Exclusive meeting rooms",
      imageUrl: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80",
      tag: "ENQUIRE",
      tagTone: "gold",
    },
  ],
  news: [
    {
      id: "1",
      title: "Lamborghini Revuelto",
      subtitle: "A new addition has joined the Toy Box family.",
      timeLabel: "2 hrs ago",
      imageUrl: "https://images.unsplash.com/photo-1621135802920-133df287f89c?w=200&q=80",
    },
    {
      id: "2",
      title: "Workshop Update",
      subtitle: "Welcome to Tesla's new Roadster Windows.",
      timeLabel: "5 hrs ago",
      imageUrl: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=200&q=80",
    },
    {
      id: "3",
      title: "Membership Drive: Phase 3 Launch",
      subtitle: "Applications are now open for Q1 2025.",
      timeLabel: "1 day ago",
      imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=200&q=80",
    },
  ],
  recentActivity: [
    {
      id: "1",
      title: "Rolls-Royce Ghost — Service & Valet",
      detail: "Your vehicle has been returned to Bay 07.",
      timeLabel: "Feb 22 · 11:21",
      tone: "gold",
    },
    {
      id: "2",
      title: "Event RSVP — Yas Marina",
      detail: "You confirmed attendance to the Abu Dhabi F1 event.",
      timeLabel: "Feb 20 · 08:45",
      tone: "teal",
    },
    {
      id: "3",
      title: "Bentley Continental — Full Fitting",
      detail: "A new tyre was replaced on your Continental.",
      timeLabel: "Feb 18 · 14:00",
      tone: "gold",
    },
    {
      id: "4",
      title: "Membership Renewed — Private Tier",
      detail: "Your annual membership has been renewed.",
      timeLabel: "Feb 15 · 09:00",
      tone: "teal",
    },
  ],
};
