import type { ClubhouseReservationsSummary } from "./types";

export const clubhouseReservationsSummary: ClubhouseReservationsSummary = {
  confirmedCount: 12,
  walkInCount: 3,
  reservations: [
    {
      id: "res-1",
      time: "12:30",
      memberName: "Mr. Bashir",
      memberInitial: "B",
      memberNumber: "No. 0002847",
      avatarClass: "bg-gradient-to-b from-gold-bright to-gold-deep text-dark",
      zone: "Restaurant",
      zoneFilter: "restaurant",
      pax: 2,
      status: "confirmed",
      statusDetail: "by Nour F.",
    },
    {
      id: "res-2",
      time: "13:00",
      memberName: "Mrs. Al Rashid",
      memberInitial: "A",
      memberNumber: "No. 0001024",
      avatarClass: "bg-avatar-slate text-foreground",
      zone: "Lounge",
      zoneFilter: "lounge",
      pax: 4,
      status: "confirmed",
      statusDetail: "by Nour F.",
    },
    {
      id: "res-3",
      time: "14:30",
      memberName: "Mr. Al Mansoori",
      memberInitial: "A",
      memberNumber: "No. 0003156",
      avatarClass: "bg-avatar-rose text-foreground",
      zone: "Suite 02",
      zoneFilter: "suite",
      pax: 6,
      status: "prep",
      statusDetail: "awaiting staff",
    },
    {
      id: "res-4",
      time: "16:00",
      memberName: "Mr. Khalfan",
      memberInitial: "K",
      memberNumber: "No. 0001983",
      avatarClass: "bg-avatar-green text-foreground",
      zone: "Restaurant",
      zoneFilter: "restaurant",
      pax: 2,
      status: "confirmed",
      statusDetail: "by Nour F.",
    },
    {
      id: "res-5",
      time: "18:30",
      memberName: "Dr. Al Mazrouei",
      memberInitial: "M",
      memberNumber: "No. 0002201",
      avatarClass: "bg-avatar-purple text-foreground",
      zone: "Lounge",
      zoneFilter: "lounge",
      pax: 3,
      status: "confirmed",
      statusDetail: "by Nour F.",
    },
  ],
};
