import type { EventsData } from "./types";

export const eventsPageMock: EventsData = {
  groups: [
    {
      id: "this-week",
      label: "THIS WEEK",
      events: [
        {
          id: "1",
          title: "Auction Day — Yas Marina",
          titlePrefix: "Auction Day —",
          titleHighlight: "Yas Marina",
          location: "Yas Marina Circuit, Abu Dhabi",
          dateLabel: "SAT 26 APR",
          timeLabel: "19:00",
          timeEndLabel: "23:00",
          description:
            "An evening of curated lots from Europe's leading houses, hosted in our private viewing pavilion. Followed by dinner at the Clubhouse for confirmed bidders.",
          tag: "FEATURED TONIGHT",
          tagTone: "gold",
          imageUrl:
            "https://natural-peach-p8yogq6h.edgeone.dev/09cfed0603b12047987501fd7a4ccb980792a782.jpg",
          membersCount: 47,
          attendingCount: 18,
          userStatus: "going",
          isFeatured: true,
          filter: ["all", "auctions"],
          detailLines: [
            { icon: "pin", text: "Yas Marina Circuit, Abu Dhabi" },
            { icon: "users", text: "18 Members Attending — (12 F1, 6 GT3/Evo)" },
            { icon: "badge", text: "Founding Member Priority — open to all" },
          ],
        },
        {
          id: "2",
          title: "Dawn Drive — Hatta Mountains",
          titlePrefix: "Dawn Drive —",
          titleHighlight: "Hatta Mountains",
          location: "Memorial Park Ramp",
          dateLabel: "SAT 26 APR",
          timeLabel: "06:00",
          tag: "APR 26",
          tagTone: "gold",
          imageUrl:
            "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80",
          attendingCount: 12,
          userStatus: null,
          filter: ["all", "drives"],
        },
        {
          id: "3",
          title: "Collectors' Dinner",
          titlePrefix: "Collectors'",
          titleHighlight: "Dinner",
          location: "Clubhouse",
          dateLabel: "SAT 26 APR",
          timeLabel: "20:00",
          tag: "APR 26",
          tagTone: "gold",
          imageUrl:
            "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80",
          attendingCount: 24,
          userStatus: "rsvp",
          filter: ["all", "dining"],
        },
        {
          id: "4",
          title: "Cigar & Whiskey",
          titlePrefix: "Cigar &",
          titleHighlight: "Whiskey",
          location: "Members' Lounge",
          dateLabel: "SAT 26 APR",
          timeLabel: "19:00",
          tag: "APR 26",
          tagTone: "gold",
          imageUrl:
            "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=600&q=80",
          attendingCount: 8,
          userStatus: null,
          filter: ["all", "dining"],
        },
      ],
    },
    {
      id: "next-month",
      label: "NEXT MONTH",
      events: [
        {
          id: "5",
          title: "Track Day — Yas Marina",
          titlePrefix: "Track Day —",
          titleHighlight: "Yas Marina",
          location: "Yas Marina",
          dateLabel: "SAT 10 MAY",
          timeLabel: "09:00",
          tag: "APR 23",
          tagTone: "gold",
          imageUrl:
            "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&q=80",
          attendingCount: 31,
          userStatus: null,
          filter: ["all", "track"],
        },
        {
          id: "6",
          title: "Concours d'Elegance",
          titlePrefix: "Concours",
          titleHighlight: "d'Elegance",
          location: "By Invitation Only",
          dateLabel: "SUN 24 MAY",
          timeLabel: "All Day",
          tag: "MAY 1",
          tagTone: "gold",
          imageUrl:
            "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&q=80",
          attendingCount: 16,
          userStatus: null,
          filter: ["all", "concours"],
        },
        {
          id: "7",
          title: "Sunset Drive — Liwa",
          titlePrefix: "Sunset Drive —",
          titleHighlight: "Liwa",
          location: "Expedition Basecamp",
          dateLabel: "SAT 30 MAY",
          timeLabel: "16:30",
          tag: "SUN 27",
          tagTone: "gold",
          imageUrl:
            "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&q=80",
          attendingCount: 20,
          userStatus: null,
          filter: ["all", "drives"],
        },
      ],
    },
  ],
};
